title: Data Analytics / Science Portfolio
logo: /assets/img/professionalphoto_circle.png
description: Data Analyst & Scientist | Analytics, ML, Problem Solving
show_downloads: true
theme: jekyll-theme-minimal
